sonar.projectKey=beatrijz_api-aluguel-imoveis
sonar.organization=beatrijz
sonar.projectName=api-aluguel-imoveis

sonar.sources=src,server.js
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=server.js
